export const BEACHES = [

  // ─── RIO DE JANEIRO ────────────────────────────────────────────────────────
  {
    id: 'copacabana',
    name: 'Copacabana',
    region: 'Rio de Janeiro',
    zone: 'Zona Sul',
    lat: -22.9711,
    lon: -43.1823,
    facing: 'SE',
    idealRange: [1.5, 1.8, 2.2, 3.0],
  },
  {
    id: 'ipanema',
    name: 'Ipanema',
    region: 'Rio de Janeiro',
    zone: 'Zona Sul',
    lat: -22.9838,
    lon: -43.2096,
    facing: 'S',
    idealRange: [0.9, 1.3, 1.7, 2.2],
  },
  {
    id: 'leblon',
    name: 'Leblon',
    region: 'Rio de Janeiro',
    zone: 'Zona Sul',
    lat: -22.9874,
    lon: -43.2248,
    facing: 'S',
    idealRange: [0.9, 1.3, 1.7, 2.2],
  },
  {
    id: 'sao_conrado',
    name: 'São Conrado',
    region: 'Rio de Janeiro',
    zone: 'Zona Sul',
    lat: -23.0101,
    lon: -43.2791,
    facing: 'S',
    idealRange: [0.9, 1.2, 1.9, 2.5],
  },
  {
    id: 'barra',
    name: 'Barra da Tijuca',
    region: 'Rio de Janeiro',
    zone: 'Zona Oeste',
    lat: -23.0093,
    lon: -43.3654,
    facing: 'S',
    idealRange: [0.9, 1.2, 1.8, 2.8],
  },
  {
    id: 'recreio',
    name: 'Recreio',
    region: 'Rio de Janeiro',
    zone: 'Zona Oeste',
    lat: -23.0178,
    lon: -43.4711,
    facing: 'SW',
    idealRange: [0.9, 1.2, 1.8, 2.8],
  },
  {
    id: 'macumba',
    name: 'Macumba',
    region: 'Rio de Janeiro',
    zone: 'Zona Oeste',
    lat: -23.0228,
    lon: -43.5021,
    facing: 'SW',
    idealRange: [0.8, 1.5, 2.5, 3.0],
  },
  {
    id: 'prainha',
    name: 'Prainha',
    region: 'Rio de Janeiro',
    zone: 'Zona Oeste',
    lat: -23.0367,
    lon: -43.5178,
    facing: 'W',
    idealRange: [0.8, 1.2, 2.0, 3.5],
  },
  {
    id: 'grumari',
    name: 'Grumari',
    region: 'Rio de Janeiro',
    zone: 'Zona Oeste',
    lat: -23.0447,
    lon: -43.5347,
    facing: 'W',
    idealRange: [0.8, 1.2, 2.5, 3.5],
  },

  // ─── FLORIANÓPOLIS ─────────────────────────────────────────────────────────
  {
    id: 'joaquina',
    name: 'Joaquina',
    region: 'Florianópolis',
    zone: 'Leste',
    lat: -27.6353,
    lon: -48.4612,
    facing: 'E',
    idealRange: [0.8, 1.2, 2.2, 3.0],
  },
  {
    id: 'praia_mole',
    name: 'Praia Mole',
    region: 'Florianópolis',
    zone: 'Leste',
    lat: -27.6034,
    lon: -48.4370,
    facing: 'E',
    idealRange: [0.8, 1.2, 2.0, 2.8],
  },
  {
    id: 'barra_da_lagoa',
    name: 'Barra da Lagoa',
    region: 'Florianópolis',
    zone: 'Leste',
    lat: -27.5726,
    lon: -48.4277,
    facing: 'NE',
    idealRange: [0.8, 1.2, 1.8, 2.2],
  },
  {
    id: 'campeche',
    name: 'Campeche',
    region: 'Florianópolis',
    zone: 'Sul',
    lat: -27.6898,
    lon: -48.4816,
    facing: 'SE',
    idealRange: [0.8, 1.2, 1.8, 2.5],
  },

  // ─── UBATUBA / MARESIAS ────────────────────────────────────────────────────
  {
    id: 'itamambuca',
    name: 'Itamambuca',
    region: 'Ubatuba',
    zone: 'Litoral Norte SP',
    lat: -23.3544,
    lon: -44.8321,
    facing: 'SE',
    idealRange: [0.8, 1.2, 2.2, 3.0],
  },
  {
    id: 'prumirim',
    name: 'Prumirim',
    region: 'Ubatuba',
    zone: 'Litoral Norte SP',
    lat: -23.3880,
    lon: -44.8654,
    facing: 'SE',
    idealRange: [0.8, 1.2, 2.0, 2.8],
  },
  {
    id: 'maresias',
    name: 'Maresias',
    region: 'São Sebastião',
    zone: 'Litoral Norte SP',
    lat: -23.8019,
    lon: -45.5564,
    facing: 'SE',
    idealRange: [0.8, 1.2, 1.8, 2.5],
  },
];

// Mapa de IDs para lookup rápido
export const BEACH_MAP = Object.fromEntries(BEACHES.map(b => [b.id, b]));
